#!/usr/bin/env bash
# enregistrer /etc/hosts file to /etc/hosts.backup
cp /etc/hosts /etc/hosts.backup
# supp entrées pour localhost of /etc/hosts
echo -n > /etc/hosts
# ajt new entrée localhost resolving to 127.0.0.1
echo "127.0.0.2 localhost" >> /etc/hosts
# ajt new entree facebook resolving to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts